version: '3'
services:
  backend:
    build: 
      context: ./schoolmanagement-backend
      dockerfile: Dockerfile.backend
    ports:
      - "8082:8082"
    networks:
      - app-network

  frontend:
    build: 
      context: .schoolmanagement-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:4200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
