services:
  backend:
    build: 
      context: ./schoolmanagement-backend
      dockerfile: Dockerfile.backend      
    ports:
      - "8082:8082"  
    networks:
      - app-network 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/schoolmanagement
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop  
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: schoolmanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    networks:
      - app-network

  frontend:
    build: 
      context: ./schoolmanagement-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:4200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
