version: '3.8'

services:
  backend:
    build: 
      context: ./schoolmanagement-backend
      dockerfile: Dockerfile.backend      
    ports:
      - "8082:8082"
    networks:
      - app-network
    depends_on:
      - database

  database:
    image: oracleinanutshell/oracle-xe-11g
    container_name: my-oracle-db
    ports:
      - "1522:1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_PASSWORD=123
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@database:1521/xe
      - SPRING_DATASOURCE_USERNAME=abdo
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect  
    volumes:
      - oracle-data:/u01/app/oracle
    networks:
      - app-network
    dns:
         - 10.0.0.1
  frontend:
    build: 
      context: ./schoolmanagement-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:4200"
    networks:
      - app-network

volumes:
  oracle-data:

networks:
  app-network:
    driver: bridge
