spring:
  application:
    name: schoolmanagement
  datasource:
    url: jdbc:postgresql://database:5432/schoolmanagement
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop  # or create-drop depending on your needs
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
 
server:
  port: 8082
  error:
    include-message: always

jwt:
  secret: 2+LaR6mKTpaFTMK4NKlHUQ5JgMtQFK0zGGSE/OUgJR8oU7Vhihb0gA8RofYlZZ/30kN+My5iIvuvYPDDMld5hg==
  expiration: 3600
