# Use a base image with Java installed
FROM openjdk:17-jdk-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file to the container
COPY target/*.jar /app/app.jar

# Expose the port that the application runs on
EXPOSE 8082

# Set the command to run the application
CMD ["java", "-jar", "app.jar"]
